<?php exit();?>
Initializing...|info|13
<?php exit();?>
Creating a job to start Backup|info|17
Starting to Backup Database|info|20
Creating softsql|working|23
Adding (L1) : wpeb_commentmeta table|working|50
Adding (L1) : wpeb_comments table|working|50
Adding (L1) : wpeb_links table|working|50
Adding (L1) : wpeb_options table|working|50
Adding (L1) : wpeb_postmeta table|working|50
Adding (L1) : wpeb_posts table|working|50
Adding (L1) : wpeb_termmeta table|working|50
Adding (L1) : wpeb_terms table|working|50
Adding (L1) : wpeb_term_relationships table|working|50
Adding (L1) : wpeb_term_taxonomy table|working|50
Adding (L1) : wpeb_usermeta table|working|50
Adding (L1) : wpeb_users table|working|50
Backing up your Wordpress Install|info|39
Starting to create archive|info|60
Adding (L1) : /home/rhrrist/public_html/wp-content/themes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/template-parts/footer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/template-parts/post|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/separator|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/heading|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/columns|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/button|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/video|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/cover|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/legacy|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/navigation|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/search|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/latest-posts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/03-generic|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/01-settings|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/02-tools|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/sass/04-elements|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/assets/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentyone/classes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree/parts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree/assets/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree/assets/fonts/inter|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree/assets/fonts/source-serif-pro|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentytwo|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentytwo/styles|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentytwo/parts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentytwo/inc|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentytwo/assets/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentytwo/assets/fonts/ibm-plex|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentytwo/assets/videos|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/backuply|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/backuply/lib|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/akismet/_inc/img|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/akismet/views|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/main|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/editors/ZipArchive|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/editors/OnlineConvert|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/plugins|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/plugins/WinRemoveTailDots|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/plugins/AutoResize|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/plugins/AutoRotate|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js/worker|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js/i18n|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js/i18n/help|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js/extras|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/sounds|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/css/jquery-ui|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/css/jquery-ui/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/2023/04|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/random_compat|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/images/media|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/block-supports|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/categories|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comment-reply-link|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/pattern|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/freeform|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/query-pagination|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/page-list-item|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comment-content|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/separator|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/site-logo|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/shortcode|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/text-columns|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/buttons|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comment-edit-link|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/columns|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/query-pagination-next|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/media-text|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comments-pagination-next|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/button|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/loginout|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/video|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/code|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/file|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comment-template|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-author|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-author-biography|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-template|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/cover|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comments-pagination-numbers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/html|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/query|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-author-name|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/page-list|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/list|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/template-part|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comments|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/navigation|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comments-pagination|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-content|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comments-pagination-previous|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/spacer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/more|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/audio|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/quote|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/html-api|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Utility|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Cookie|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Response|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Exception|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Exception/Http|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Exception/Transport|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Auth|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Transport|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/library|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/HTTP|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/XML/Declaration|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/Parse|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/Cache|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Text|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/php-compat|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/rest-api|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/rest-api/endpoints|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/rest-api/fields|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/rest-api/search|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/thickbox|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/themes/inlite|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/themes/modern|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins/lightgray|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins/lightgray/img|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins/lightgray/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins/wordpress/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/utils|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/wpemoji|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/charmap|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/fullscreen|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/image|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/media|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/lists|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/tabfocus|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/paste|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/mediaelement|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/mediaelement/renderers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/plupload|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/jcrop|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/swfupload|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/crop|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/imgareaselect|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sitemaps/providers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/ID3|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/assets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/customize|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/edit-site|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/nux|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/block-library|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/edit-post|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/block-editor|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/widgets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/block-directory|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/list-reusable-blocks|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/widgets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/lib|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/namespaced|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/namespaced/Core/Poly1305|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32/Poly1305|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32/Curve25519|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32/Curve25519/Ge|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core/Poly1305|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core/ChaCha20|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core/Curve25519|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core/Curve25519/Ge|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/style-engine|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/IXR|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/js/widgets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/css/colors/midnight|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/css/colors/light|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/css/colors/ocean|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-admin/css/colors/modern|adding|65
Archive created with a file size of 23.94 MB|info|100
Backup Successfully Completed|success|100
