<?php exit();?>
Initializing...|info|13
<?php exit();?>
Creating a job to start Backup|info|17
Starting to Backup Database|info|20
Creating softsql|working|23
Adding (L1) : wpeb_actionscheduler_actions table|working|50
Adding (L1) : wpeb_actionscheduler_claims table|working|50
Adding (L1) : wpeb_actionscheduler_groups table|working|50
Adding (L1) : wpeb_actionscheduler_logs table|working|50
Adding (L1) : wpeb_bm_guests table|working|50
Adding (L1) : wpeb_bm_mentions table|working|50
Adding (L1) : wpeb_bm_message_messages table|working|50
Adding (L1) : wpeb_bm_message_meta table|working|50
Adding (L1) : wpeb_bm_message_recipients table|working|50
Adding (L1) : wpeb_bm_moderation table|working|50
Adding (L1) : wpeb_bm_threads table|working|50
Adding (L1) : wpeb_bm_thread_meta table|working|50
Adding (L1) : wpeb_commentmeta table|working|50
Adding (L1) : wpeb_comments table|working|50
Adding (L1) : wpeb_links table|working|50
Adding (L1) : wpeb_mo_openid_linked_user table|working|50
Adding (L1) : wpeb_options table|working|50
Adding (L1) : wpeb_postmeta table|working|50
Adding (L1) : wpeb_posts table|working|50
Adding (L1) : wpeb_social_users table|working|50
Adding (L1) : wpeb_termmeta table|working|50
Adding (L1) : wpeb_terms table|working|50
Adding (L1) : wpeb_term_relationships table|working|50
Adding (L1) : wpeb_term_taxonomy table|working|50
Adding (L1) : wpeb_um_metadata table|working|50
Adding (L1) : wpeb_usermeta table|working|50
Adding (L1) : wpeb_users table|working|50
Adding (L1) : wpeb_wpforms_tasks_meta table|working|50
Adding (L1) : wpeb_yoast_indexable table|working|50
Adding (L1) : wpeb_yoast_indexable_hierarchy table|working|50
Adding (L1) : wpeb_yoast_migrations table|working|50
Adding (L1) : wpeb_yoast_primary_term table|working|50
Adding (L1) : wpeb_yoast_seo_links table|working|50
Backing up your Wordpress Install|info|39
Starting to create archive|info|60
Adding (L1) : /home/rhrrist/public_html/wp-content/themes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree-child/parts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree-child/templates|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree-child/ultimate-member|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree-child/assets/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree-child/assets/fonts/inter|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/themes/twentytwentythree-child/assets/fonts/ibm-plex-mono|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/upgrade|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/lib|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/lib/emogrifier|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/lib/usage-tracking|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/lib/usage-tracking/tests|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/templates|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/templates/emails|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/templates/emails/plain|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/templates/form-fields|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/includes/3rd-party|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/includes/admin/views|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/includes/emails|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/assets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/assets/lib|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/assets/lib/jquery-chosen|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/assets/lib/select2|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/assets/dist|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/assets/dist/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wp-job-manager/assets/dist/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/inc/api|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/views|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/addons|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/addons/buddyboss|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/addons/buddyboss/notifications|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/addons/uncanny/better-messages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/addons/automatorwp|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/assets/emojies|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/assets/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/languages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/random-name-generator|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/templates/plugin-info|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/templates/partials|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/templates/debug|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/templates/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/templates/connect|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/includes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/includes/supplements|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/includes/sdk|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/includes/customizer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/assets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/assets/img|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/assets/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/assets/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/assets/css/admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/freemius/languages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/php-jwt|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/randomizer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/bp-better-messages/vendor/randomizer/Exception|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/lib/dependency-injection|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/lib/migrations|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/packages/js/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/inc/options|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/inc/exceptions|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/js/dist|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/config|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/i18n|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/presenters/admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/integrations|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/integrations/third-party|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/integrations/admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/routes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/generators/schema|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/conditionals|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/conditionals/third-party|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/helpers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/actions|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/src/actions/configuration|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/deprecated/admin/ryte|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/presenters|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/presenters/webmaster|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/presenters/open-graph|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/presenters/debug|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/presenters/admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/presentations|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/loggers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/integrations|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/integrations/blocks|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/integrations/watchers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/integrations/front-end|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/routes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/initializers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/generated|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/generators|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/generators/schema|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/builders|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/conditionals|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/conditionals/third-party|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/conditionals/admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/services/indexables|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/services/importing/aioseo|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/services/health-check|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/context|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/surfaces/values|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/exceptions/addon-installation|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/exceptions/oauth|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/exceptions/oauth/tokens|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/exceptions/importing|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/values|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/values/oauth|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/values/indexables|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/wordpress|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/actions|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/actions/configuration|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/actions/indexing|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/actions/indexables|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/actions/importing|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/src/actions/semrush|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/formatter|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/google_search_console|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/capabilities|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/watchers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/views|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/views/form|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/views/tabs|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/views/tabs/network|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/menu|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/tracking|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/ajax|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/import/plugins|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/statistics|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/pages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/admin/taxonomy|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/css/dist|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/psr|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/psr/log/Psr|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/psr/log/Psr/Log|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/psr/container|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/guzzlehttp/psr7|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/guzzlehttp/psr7/src|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/guzzlehttp/guzzle/src|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/guzzlehttp/guzzle/src/Cookie|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/guzzlehttp/promises|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/guzzlehttp/promises/src|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/symfony/dependency-injection|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/symfony/dependency-injection/Argument|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/symfony/dependency-injection/ParameterBag|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/wordproof/wordpress-sdk/app/Helpers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/wordproof/wordpress-sdk/app/Controllers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/wordproof/wordpress-sdk/app/Support|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/wordproof/wordpress-sdk/app/DataTransferObjects|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/league|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/league/oauth2-client|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/league/oauth2-client/src/Provider|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/league/oauth2-client/src/Grant|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/league/oauth2-client/src/Grant/Exception|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/wordpress-seo/vendor_prefixed/league/oauth2-client/src/Token|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/backuply/lib|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/backuply/lib/Curl|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/backuply/main|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/backuply/assets/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/akismet/_inc|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/akismet/_inc/img|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/akismet/views|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/add_on|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_sha|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_sha/cust_text|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_sha/soc_med_cust|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_sha/twitter_btn|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_sha/soc_med_ser|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_sha/shrt_co|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/rest_api|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/email_settings|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/profile|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/integration|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_com/com_shrtco|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_com/com_select_app|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/soc_com/com_display_options|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/premium_features|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/view/link_social_account|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/lang|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/includes/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/includes/images/bp_add|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/includes/images/wca|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/includes/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/includes/js/social|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/miniorange-login-openid/includes/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/templates/profile|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/lib|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/lib/mobiledetect|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/templates|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/templates/directory|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/templates/access|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/templates/modal|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/templates/role|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/templates/form|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/list-tables|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.0.24|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.0.10|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.1.3-beta3|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/1.3.39|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.0.44|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.3.0|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.4.0|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.6.0|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/core/packages/2.5.0|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/admin/assets/img|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/includes/widgets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/assets/sass|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/assets/dynamic_css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/assets/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/assets/css/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/assets/font|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/ultimate-member/languages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/main|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/files|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/editors|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/plugins|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/plugins/Normalizer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/plugins/AutoResize|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/php/.tmp|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js/worker|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js/i18n|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/manager/js/i18n/help|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/fileorganizer/css/jquery-ui|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates/plugin-info|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates/partials|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates/debug|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates/forms|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates/forms/deactivation|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/templates/connect|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/includes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/includes/debug|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/includes/entities|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/includes/customizer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/includes/managers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/assets|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/assets/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/freemius/languages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/inc|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/images/styles|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/config|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/partials|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/partials/shortcodes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/partials/shortcodes/posts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/js/generator|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/js/shortcodes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/js/block-editor|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/includes/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/images/pages/about|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/images/pro-features|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/partials/help|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/partials/settings|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/partials/settings/sections|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/partials/settings/fields|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/partials/widget|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/partials/pages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/partials/pro-features|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/admin/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor/jquery-inview|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor/chartjs|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor/swiper|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor/fork-awesome|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor/fork-awesome/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor/owl-carousel|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcodes-ultimate/vendor/popper|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcode-in-menus|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcode-in-menus/includes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/plugins/shortcode-in-menus/languages|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/jobpost|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/mailchimp-for-wp|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/wpforms|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/ultimatemember/9|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/ultimatemember/10|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/2023|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-content/uploads/2023/04|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/images/wlw|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/images/media|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/images/crystal|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/images/smilies|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/block-supports|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comment-reply-link|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/nextpage|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/freeform|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-title|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/rss|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/list-item|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comment-content|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/separator|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/buttons|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/preformatted|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/pullquote|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/columns|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/query-pagination-next|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/media-text|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comments-pagination-next|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/file|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/block|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/term-description|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/query-title|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/cover|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/navigation-link|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/social-links|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-comments-form|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/query|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-author-name|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/page-list|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/template-part|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/post-excerpt|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/site-tagline|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/comments-pagination-previous|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/spacer|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/query-pagination-previous|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/audio|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/blocks/quote|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/html-api|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Exception|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Requests/src/Transport|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/Net|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/Content|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/Content/Type|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/HTTP|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/XML|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/XML/Declaration|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/Parse|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/SimplePie/Decode/HTML|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Text/Diff|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/Text/Diff/Engine|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/rest-api/fields|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/rest-api/search|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/themes/modern|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/langs|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins/lightgray|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins/lightgray/fonts|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/skins/wordpress/images|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/hr|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/wpgallery|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/compat3x/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/charmap|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/fullscreen|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/image|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/wpdialogs|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/wptextpattern|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/media|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/lists|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/wpview|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/link|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/tinymce/plugins/colorpicker|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/mediaelement|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/mediaelement/renderers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/plupload|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/codemirror|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/dist|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/dist/vendor|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/js/imgareaselect|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sitemaps|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/sitemaps/providers|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/ID3|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/nux|adding|65
Adding (L1) : /home/rhrrist/public_html/wp-includes/css/dist/editor|adding|65
About to call self to prevent timeout|info|0
Backing up your Wordpress Install|info|39
Starting to create archive|info|60
Adding (L2) : /home/rhrrist/public_html/wp-includes/css/dist/customize-widgets|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/css/dist/reusable-blocks|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/namespaced/Core/ChaCha20|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/namespaced/Core/Curve25519|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32/SecretStream|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32/Poly1305|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32/ChaCha20|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core32/Curve25519|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/PHP52|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core/Base64|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/sodium_compat/src/Core/Poly1305|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/style-engine|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-includes/IXR|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-admin|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-admin/images|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-admin/js|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-admin/includes|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-admin/css|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-admin/css/colors/sunrise|adding|65
Adding (L2) : /home/rhrrist/public_html/wp-admin/css/colors/ectoplasm|adding|65
Archive created with a file size of 32.11 MB|info|100
Backup Successfully Completed|success|100
